### ISSUE TITLE
Ubuntu-latest workflows will use Ubuntu-20.04 soon.

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-tumblebug#378]
An annotation below appeared.

![image](https://user-images.githubusercontent.com/7975459/106145027-64537580-61b8-11eb-829e-997f0d86c8f6.png)

On workflow, we need to specify the version of Ubuntu soon ✔️

**Comment by seokho-son** [comment]
LGTM ^^

**Comment by seokho-son** [comment]
Let's keep use “ubuntu-18.04” since it is the current recommended os-version for CB-Tumblebug development.
Once we change recommended os-version for CB-Tumblebug development, we may use Ubuntu-20.04 for image build.

related: https://github.com/actions/virtual-environments/issues/1816
```
Ubuntu-20.04 is ready to be the default version for the “ubuntu-latest” label in GitHub Actions and Azure DevOps. This change will be rolled out over a period of several weeks beginning on November, 30. (December, 22 - January, 4 will be a migration break due to holidays)

If you see any issues with your workflows during this transition period:

File an issue in this repository
Switch back to Ubuntu 18.04 by specifying the “ubuntu-18.04” label. We will continue to support Ubuntu 18.04.
Note that image software between Ubuntu-18.04 and Ubuntu-20.04 differs not only by the pre-installed versions of tools, but also by the default versions of some tools. See the list of missing and changes software below.
```

/unassign @jihoon-seo
/assign @seokho-son
