### ISSUE TITLE
Update the Links and contents of `src/testclient/scripts/README.md` 

### ISSUE THREAD

**Issue by ChobobDev** [cloud-barista/cb-tumblebug#831]
**What would you like to be enhanced**
:  As you may know, the `README.md` on the root directory of this project has a translated version, I believe there should be some enhancement of the `README.md`  on `src/testclient/scripts` . 

**Why is this needed**
: 

**Proposed solution**
:  For this occasion, I believe adding another `README.md`  under `i18n`  directory is a bit too much. So I will add extra lines to this file guiding the users to the English `README.md` respectively.

**Comment by seokho-son** [comment]
@ChobobDev Thank you for the suggestion !!

I think https://github.com/cloud-barista/cb-tumblebug/blob/main/src/testclient/scripts/README.md is not a complete document.
Also, we can make the document simple since the base contents for this document live in [the main readme document: CB-Tumblebug 스크립트 사용](https://github.com/cloud-barista/cb-tumblebug#cb-tumblebug-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%82%AC%EC%9A%A9).

In case of a simple document, maintaining two documents is not an effective way as you mentioned.

How about use English contents only? And provide links to both English and Korean contents.

for instance,

```diff

- ## 실행 방법
+ ## How to use 

- [실행 방법](../../../README.md#2-cb-tumblebug-스크립트를-통한-테스트)
+ Using CB-Tumblebug Script [[English](https://github.com/cloud-barista/cb-tumblebug/blob/main/i18n/README-EN.md#using-cb-tumblebug-script),
+ [한국어](https://github.com/cloud-barista/cb-tumblebug#cb-tumblebug-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%82%AC%EC%9A%A9)]
```
Using CB-Tumblebug Script [[English](https://github.com/cloud-barista/cb-tumblebug/blob/main/i18n/README-EN.md#using-cb-tumblebug-script), [한국어](https://github.com/cloud-barista/cb-tumblebug#cb-tumblebug-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%82%AC%EC%9A%A9)]

**Comment by ChobobDev** [comment]
@seokho-son As this issue is merged I will close this issue so The issue lists are nice and tidy.

Thank you
